### ISSUE TITLE
/* Some spanish translate not shipped in asteroid-music */

### ISSUE THREAD

**Issue by Caballlero** [AsteroidOS/asteroid-music#9]
- Dev build 15 May.  Just notifying...

 #######<location filename="../main.qml" line="147"/>
 #######<source>&lt;h3&gt;No data&lt;/h3&gt;
#Sync AsteroidOS with your phone.</source>
 #######<translation>&lt;h3&gt;No hay datos&lt;/h3&gt; <<<<<<<<<<< Only these lines 
#Sincroniza AsteriodOS con tu teléfono.</translation>    <<<<<<<<<<< Only these lines       : )
 ###</message>
#</context>
#</TS>

**Comment by FlorentRevest** [comment]
Thanks for reporting

**Comment by Caballlero** [comment]
Merci pour le résoudre .
